const products = [
  {
    id: 1,
    name: "پیراهن مردانه جوتی جینز",
    price: 1649000,
    image: "images/product1.jpg",
    gender: "male",
    category: "پیراهن",
  },
  {
    id: 2,
    name: "پیراهن مردانه بالون Balloon",
    price: 890000,
    image: "images/product2.jpg",
    gender: "male",
    category: "پیراهن",
  },
  {
    id: 3,
    name: "پولوشرت مردانه جوتی جینز",
    price: 1209500,
    image: "images/product3.jpg",
    gender: "male",
    category: "تی‌شرت",
  },
  {
    id: 4,
    name: "تیشرت مردانه جوتی جینز",
    price: 140000,
    image: "images/product4.jpg",
    gender: "male",
    category: "تی‌شرت",
  },
  {
    id: 5,
    name: "کت لینن مردانه جوتی جینز",
    price: 3024500,
    image: "images/product5.jpg",
    gender: "male",
    category: "کت",
  },
  {
    id: 6,
    name: "کت مردانه فریولی Feriolli",
    price: 5995000,
    image: "images/product6.jpg",
    gender: "male",
    category: "کت",
  },
  {
    id: 7,
    name: "جوراب ساق کوتاه مردانه کوتون",
    price: 1350000,
    image: "images/product7.jpg",
    gender: "male",
    category: "جوراب",
  },
  {
    id: 8,
    name: "جوراب ساق کوتاه مردانه کوتون",
    price: 987500,
    image: "images/product8.jpg",
    gender: "male",
    category: "جوراب",
  },
  {
    id: 9,
    name: "جوراب ساق کوتاه مردانه کوتون",
    price: 765000,
    image: "images/product9.jpg",
    gender: "male",
    category: "جوراب",
  },
  {
    id: 10,
    name: "شلوار زنانه جوتی جینز",
    price: 1649500,
    image: "images/product10.jpg",
    gender: "female",
    category: "شلوار",
  },
  {
    id: 11,
    name: "شلوار زنانه مالینو Malino",
    price: 4089000,
    image: "images/product11.jpg",
    gender: "female",
    category: "شلوار",
  },
  {
    id: 12,
    name: "شلوار اسلش زنانه جین وست",
    price: 1649500,
    image: "images/product12.jpg",
    gender: "female",
    category: "شلوار",
  },
  {
    id: 13,
    name: "تیشرت زنانه جوتی جینز",
    price: 1374500,
    image: "images/product13.jpg",
    gender: "female",
    category: "تی‌شرت",
  },
  {
    id: 14,
    name: "تیشرت زنانه واسا",
    price: 500000,
    image: "images/product14.jpg",
    gender: "female",
    category: "تی‌شرت",
  },
  {
    id: 15,
    name: "تیشرت زنانه جین وست",
    price: 1374000,
    image: "images/product15.jpg",
    gender: "female",
    category: "تی‌شرت",
  },
  {
    id: 16,
    name: "تیشرت زنانه جینز",
    price: 934500,
    image: "images/product16.jpg",
    gender: "female",
    category: "تی‌شرت",
  },
  {
    id: 17,
    name: "مانتو زنانه جوتی جینز",
    price: 2199500,
    image: "images/product17.jpg",
    gender: "female",
    category: "مانتو",
  },
  {
    id: 18,
    name: "مانتو زنانه ریس Rees",
    price: 1133400,
    image: "images/product18.jpg",
    gender: "female",
    category: "مانتو",
  },
  {
    id: 19,
    name: "مانتو زنانه مانگ Mong",
    price: 2534400,
    image: "images/product19.jpg",
    gender: "female",
    category: "مانتو",
  },
  {
    id: 20,
    name: "مانتو تابستانی جوتی جینز",
    price: 879400,
    image: "images/product20.jpg",
    gender: "female",
    category: "مانتو",
  },
  {
    id: 21,
    name: "کفش چرم طبیعی مردانه بالون",
    price: 3950000,
    image: "images/product21.jpg",
    gender: "male",
    category: "کفش",
  },
  {
    id: 22,
    name: "کفش چرم طبیعی مردانه ایران طب",
    price: 3301700,
    image: "images/product22.jpg",
    gender: "male",
    category: "کفش",
  },
  {
    id: 23,
    name: "کفش مردانه چرم طبیعی شیفر",
    price: 3455000,
    image: "images/product23.jpg",
    gender: "male",
    category: "کفش",
  },
  {
    id: 24,
    name: "کفش پاشنه دار چرم طبیعی زنانه شیفر",
    price: 3995000,
    image: "images/product24.jpg",
    gender: "female",
    category: "کفش",
  },
  {
    id: 25,
    name: "صندل زنانه اورز Orez",
    price: 2723000,
    image: "images/product25.jpg",
    gender: "female",
    category: "کفش",
  },
  {
    id: 26,
    name: "کفش زنانه اورز Orez",
    price: 2659300,
    image: "images/product26.jpg",
    gender: "female",
    category: "کفش",
  },
  {
    id: 27,
    name: "کیف دستی زنانه سولا Sola",
    price: 1552000,
    image: "images/product27.jpg",
    gender: "female",
    category: "کیف",
  },
  {
    id: 28,
    name: "کیف دستی زنانه صاد Saad",
    price: 2040000,
    image: "images/product28.jpg",
    gender: "female",
    category: "کیف",
  },
  {
    id: 29,
    name: "کیف زنانه بیسراک Bisrak",
    price: 1144000,
    image: "images/product29.jpg",
    gender: "female",
    category: "کیف",
  },
  {
    id: 30,
    name: "کیف زنانه باترفلای Butterfly",
    price: 2331000,
    image: "images/product30.jpg",
    gender: "female",
    category: "کیف",
  },
];
